name: Build A16 and A17 packages
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  android16:
    name: Android 16 · KMI5
    uses: ./.github/workflows/build_kernel.yml
    with:
      project: mi17_sm8850
      branch: android16
      ksu_variant: resukisu
      do_release: false
      apply_susfs: true
      apply_bbg: false
    secrets: inherit
  android17:
    name: Android 17 · experimental KMI6
    uses: ./.github/workflows/build_kernel.yml
    with:
      project: mi17_sm8850
      branch: android17
      ksu_variant: resukisu
      do_release: false
      apply_susfs: true
      apply_bbg: false
    secrets: inherit
